/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadefinalds;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dr chapatine
 */
public class JFEmpresas extends javax.swing.JFrame {

    /**
     * Creates new form JFEmpresas
     */
    public JFEmpresas() {
        initComponents();
        txtCE.setEnabled(false);
        txtNE.setEnabled(false);
        txtCNPJ.setEnabled(false);
        txtRS.setEnabled(false);
        btnAtualizar.setEnabled(false);
     //   btnAvancar.setEnabled(false);
      //  btnAvancarT.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
     //   btnVoltar.setEnabled(false);
      //  btnVoltarT.setEnabled(false);
        
    }
    
    public void proximo(){
        int a = 0;
                
    if((true)){
            
           table.setRowSelectionInterval(a, 1);
           a++;
        }
    
    }
    
    public void atualizar(){
          
        Connection con = Conexao.abrirConexao();
        
        EmpresaDAO ed = new EmpresaDAO(con);
        
        List<EmpresaBean> listaEmpresa = new ArrayList<EmpresaBean>();
        
        listaEmpresa = ed.listarEmpresa();
        
        DefaultTableModel tbm = (DefaultTableModel) table.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (EmpresaBean cb : listaEmpresa) {
            tbm.addRow(new String[1]);
            
            table.setValueAt(cb.getCod(), i, 0);
            table.setValueAt(cb.getNome(), i, 1);
            
            i++;
        }
            txtCE.setText("");
            txtNE.setText("");
            txtCNPJ.setText("");
            txtRS.setText("");
            
        Conexao.fecharConexao(con); 
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        lblCE = new javax.swing.JLabel();
        lblNE = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblRS = new javax.swing.JLabel();
        txtCE = new javax.swing.JTextField();
        txtNE = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        txtRS = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblCli = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Empresas");
        setBackground(new java.awt.Color(51, 51, 51));

        lblCE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCE.setText("Código Empresa");
        lblCE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNE.setText("Nome da Empresa");
        lblNE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCNPJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCNPJ.setText("CNPJ");
        lblCNPJ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRS.setText("Razão Social");
        lblRS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCE.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEActionPerformed(evt);
            }
        });

        txtNE.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNEActionPerformed(evt);
            }
        });

        txtCNPJ.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCNPJ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });

        txtRS.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRSActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Dependente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        lblCli.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCli.setText("Clínicas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCli, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        btnSalvar.setBorder(null);
        btnSalvar.setMaximumSize(new java.awt.Dimension(20, 20));
        btnSalvar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setMaximumSize(new java.awt.Dimension(20, 20));
        btnExcluir.setMinimumSize(new java.awt.Dimension(20, 20));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/update.png"))); // NOI18N
        btnAtualizar.setBorder(null);
        btnAtualizar.setMaximumSize(new java.awt.Dimension(20, 20));
        btnAtualizar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        btnPesquisar.setBorder(null);
        btnPesquisar.setMaximumSize(new java.awt.Dimension(20, 20));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        btnNovo.setBorder(null);
        btnNovo.setMaximumSize(new java.awt.Dimension(20, 20));
        btnNovo.setMinimumSize(new java.awt.Dimension(20, 20));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNE, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(lblCE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCNPJ)
                            .addComponent(lblCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRS)
                            .addComponent(lblRS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCNPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNEActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void txtRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRSActionPerformed

    private void txtCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        atualizar();
        btnAtualizar.setEnabled(true);
      //  btnAvancar.setEnabled(true);
      //  btnAvancarT.setEnabled(true);
        btnExcluir.setEnabled(true);
      //  btnVoltar.setEnabled(true);
      //  btnVoltarT.setEnabled(true);
        txtNE.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtRS.setEnabled(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Connection con = Conexao.abrirConexao();
        EmpresaBean eb = new EmpresaBean();
        EmpresaDAO ed = new EmpresaDAO(con);
        
        eb.setNome(txtNE.getText());
        eb.setCnpj(txtCNPJ.getText());
        eb.setRazao(txtRS.getText());
        lblMsg.setText(ed.inserirEmpresa(eb));
        
        
        btnAtualizar.setEnabled(true);
       // btnAvancar.setEnabled(true);
       // btnAvancarT.setEnabled(true);
        btnExcluir.setEnabled(true);
      //  btnVoltar.setEnabled(true);
      ///  btnVoltarT.setEnabled(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);

        Conexao.fecharConexao(con);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txtCE.setText("");
        txtNE.setText("");
        txtCNPJ.setText("");
        txtRS.setText("");
        lblMsg.setText("");     
        btnSalvar.setEnabled(true);
        txtNE.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtRS.setEnabled(true);
        btnNovo.setEnabled(false);
        btnAtualizar.setEnabled(false);
     //   btnAvancar.setEnabled(false);
      //  btnAvancarT.setEnabled(false);
        btnExcluir.setEnabled(false);
      //  btnVoltarT.setEnabled(false);
      //  btnVoltar.setEnabled(false);


       
        

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRow() != -1){
       
        Connection con = Conexao.abrirConexao();
        EmpresaBean eb = new EmpresaBean();
        EmpresaDAO ed = new EmpresaDAO(con);
        
       eb.setCod((int)table.getValueAt(table.getSelectedRow(), 0));
        
        Object[] opcoes = {"Sim", "Não"};
        
        int i = JOptionPane.showOptionDialog(
                null,
                "Deseja excluir esse Cliente: " + txtCE.getText() + "?",
                "Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);
        
        if (i == JOptionPane.YES_OPTION) {
            lblMsg.setText(ed.removerEmpresa(eb));
            txtCE.setText("");
            txtCE.setEnabled(false);
        txtNE.setEnabled(false);
        txtCNPJ.setEnabled(false);
        txtRS.setEnabled(false);
        btnAtualizar.setEnabled(false);
       // btnAvancar.setEnabled(false);
       // btnAvancarT.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
       // btnVoltar.setEnabled(false);
       // btnVoltarT.setEnabled(false);
        }
        Conexao.fecharConexao(con);
    }   
    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRow() != -1){
            
        
        Connection con = Conexao.abrirConexao();
        EmpresaBean eb = new EmpresaBean();
        EmpresaDAO ed = new EmpresaDAO(con);
        
        eb.setNome(txtNE.getText());
        eb.setCnpj(txtCNPJ.getText());
        eb.setRazao(txtRS.getText());
        eb.setCod((int)table.getValueAt(table.getSelectedRow(), 0));
        
        Object[] opcoes = {"Sim", "Não"};
        
        int i = JOptionPane.showOptionDialog(
                null,
                "Deseja Alterar essa Empresa: " + txtCE.getText() + "?",
                "Alteração",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);
        
        if (i == JOptionPane.YES_OPTION) {
            lblMsg.setText(ed.alterarEmpresa(eb));
            txtCE.setText("");
            txtNE.setText("");
            txtCNPJ.setText("");
            txtRS.setText("");
            txtCE.setEnabled(false);
        txtNE.setEnabled(false);
        txtCNPJ.setEnabled(false);
        txtRS.setEnabled(false);
        btnAtualizar.setEnabled(false);
        //btnAvancar.setEnabled(false);
        //btnAvancarT.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        //btnVoltar.setEnabled(false);
        //btnVoltarT.setEnabled(false);
        }
        Conexao.fecharConexao(con);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        Connection con = Conexao.abrirConexao();
        EmpresaBean eb = new EmpresaBean();
        EmpresaDAO ed = new EmpresaDAO(con);
        
        int index = table.getSelectedRow();
        
        eb = ed.listarEmpresa().get(index);
        
        txtCE.setText(String.valueOf(eb.getCod()));
        txtNE.setText(eb.getNome());
        txtCNPJ.setText(eb.getCnpj());
        txtRS.setText(eb.getRazao());
        Conexao.fecharConexao(con);
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCE;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCli;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNE;
    private javax.swing.JLabel lblRS;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCE;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtNE;
    private javax.swing.JTextField txtRS;
    // End of variables declaration//GEN-END:variables

    private boolean tableMouseClicked(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean btnAvancarActionPerformed(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
